services:
  application:
    build: ./
    container_name: application
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
      - migrations
  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgres/data
    restart: always
  migrations:
    container_name: migrations
    image: migrate/migrate:latest
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - database
volumes:
  db_data: