env: ""

server:
  host: "0.0.0.0"
  port: ":8080"
  request_duration: 5

postgres:
  host: "database"
  port: "5432"
  username: "admin"
  password: ""
  dbname: "auth-service-db"
  sslmode: "disable"

cors:
  allowed_origins: []
  allow_credentials: true
  allowed_methods: []
  allowed_headers: []
  exposed_headers: []
  max_age: 600

jwt_secret: ""

cookie:
  cookie_secure: false