env: "local"

server:
  host: "0.0.0.0"
  port: ":8080"

postgres:
  host: "database"
  port: "5432"
  username: "admin"
  password: ""
  dbname: "auth-service-db"
  sslmode: "disable"

cors:
  allowed_origins: []
  allow_credentials: true
  allowed_methods:
    - "GET"
    - "POST"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
    - "X-Requested-With"
  exposed_headers: []
  max_age: 600

jwt_secret: ""

cookie:
  cookie_secure: false